version: '3'

networks:
  custom_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/24
        
services:
  # PostgreSQL service for user management
  postgres-user:
    image: postgres:latest
    container_name: postgres-user-container
    networks:
      custom_network:
        ipv4_address: 172.16.0.2
    environment:
      POSTGRES_DB: dsrl_users
      POSTGRES_USER: dsrl-lab
      POSTGRES_PASSWORD: dsrl-lab
      
  # Spring Boot application service for user management
  user-management-app:
    image: my-user-image:latest
    container_name: user-management-container
    networks:
      custom_network:
        ipv4_address: 172.16.0.3
    environment:
      DB_IP: 172.16.0.2
      DB_PORT: 5432
      DB_USER: dsrl-lab
      DB_PASSWORD: dsrl-lab
      DB_DBNAME: dsrl_users
      DEVICE_CONTAINER_NAME: 172.16.0.5
      DEVICE_CONTAINER_PORT: 8081
    ports:
      - "8080:8080"
    depends_on:
      - postgres-user

  # PostgreSQL service for device management
  postgres-device:
    image: postgres:latest
    container_name: postgres-device-container
    networks:
      custom_network:
        ipv4_address: 172.16.0.4
    environment:
      POSTGRES_DB: dsrl_devices
      POSTGRES_USER: dsrl-lab
      POSTGRES_PASSWORD: dsrl-lab
   # Use a different port for the second PostgreSQL instance
      
  # Spring Boot application service for device management
  device-management-app:
    image: my-device-image:latest  
    container_name: device-management-container
    networks:
      custom_network:
        ipv4_address: 172.16.0.5
    environment:
      DB_IP: 172.16.0.4
      DB_PORT: 5432  
      DB_USER: dsrl-lab
      DB_PASSWORD: dsrl-lab
      DB_DBNAME: dsrl_devices
      USER_CONTAINER_NAME: 172.16.0.3
      USER_CONTAINER_PORT: 8080
    ports:
      - "8081:8081"  # Map to a different host port
    depends_on:
      - postgres-device
    
  frontend:
    image: my-react-image:latest
    container_name: react-frontend-container
    networks:
      custom_network:
        ipv4_address: 172.16.0.6
    environment:
      REACT_APP_HOST_USER_API: http://172.16.0.3:8080
      REACT_APP_HOST_DEVICE_API: http://172.16.0.5:8081
    ports:
      - "80:80"
    depends_on:
      - user-management-app
      - device-management-app
