FROM node:8 as builder
WORKDIR /app
COPY package*.json /app/
RUN npm install

COPY . .

# Make port 3000 available to the world outside this container
EXPOSE 3000

# Define environment variables
ENV NODE_ENV development

# Run the app
CMD ["npm", "start"]
